server:
  address: ":6001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  dumpRouterMap: false              # 是否在Server启动时打印所有的路由列表。默认为true
  logPath: "log"                    # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
  logStdout: true                   # 日志是否输出到终端。默认为true
  errorStack: true                   # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
  errorLogEnabled: true               # 是否记录异常日志信息到日志中。默认为true
  errorLogPattern: "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
  accessLogEnabled: false              # 是否记录访问日志。默认为false
  accessLogPattern: "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"

# Database
database:
  logger:
    level: "all"
    stdout: true
  default:
    type: "mysql"
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/kkdl?loc=Local&parseTime=true"
    debug: true
# Redis
redis:
  default:
    address: 127.0.0.1:6379
    db: 1
    pass: 123456
    idleTimeout: 600

# 微信
weChat:
  miniPrograms:
    appid: wxbd4xxxx
    secret: a40a8bxxxxx

# 七牛云
qiNiuConfig:
  access: 'xxxx'
  secret: 'xxxxxx'
  bucket: 'xxxxxx'
  baseUrl: 'xxxxxx'

# 邮箱配置
emailConfig:
  key: 'xxxxx'
  email: 'xxxxxx'





