// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package shortUrlCode

import (
	"compressURL/api/shortUrlCode"
)

type ControllerV1 struct{}

func NewV1() shortUrlCode.IShortUrlCodeV1 {
	return &ControllerV1{}
}
