// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package short_url_code

import (
	"compressURL/api/short_url_code"
)

type ControllerV1 struct{}

func NewV1() short_url_code.IShortUrlCodeV1 {
	return &ControllerV1{}
}
