// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package shortURL

import (
	"compressURL/api/shortURL"
)

type ControllerV1 struct{}

func NewV1() shortURL.IShortURLV1 {
	return &ControllerV1{}
}
