// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package shortUrl

import (
	"compressURL/api/shortUrl"
)

type ControllerV1 struct{}

func NewV1() shortUrl.IShortUrlV1 {
	return &ControllerV1{}
}
