CREATE TABLE `short_url_visits` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `user_id` varchar(40) NOT NULL COMMENT '用户id',
    `short_url` varchar(20) NOT NULL COMMENT '短链,唯一，不能为空',
    `raw_url` varchar(500) NOT NULL COMMENT '原始 url 不能为空',
    `user_agent` varchar(255) NOT NULL COMMENT '用户代理字符串，存储提供的完整用户代理',
    `browser_name` varchar(50) DEFAULT NULL COMMENT '浏览器名称',
    `browser_version` varchar(50) DEFAULT NULL COMMENT '浏览器版本',
    `device_model` varchar(50) DEFAULT NULL COMMENT '设备型号',
    `engine_name` varchar(50) DEFAULT NULL COMMENT '浏览器引擎名称',
    `engine_version` varchar(50) DEFAULT NULL COMMENT '浏览器引擎版本',
    `os_name` varchar(50) DEFAULT NULL COMMENT '操作系统名称',
    `os_version` varchar(50) DEFAULT NULL COMMENT '操作系统版本',
    `ip` varchar(45) NOT NULL COMMENT 'ip 不能为空',
    `continent` varchar(50) DEFAULT NULL COMMENT '大洲名称',
    `continent_code` varchar(10) DEFAULT NULL COMMENT '大洲代码',
    `country` varchar(50) DEFAULT NULL COMMENT '国家名称',
    `country_code` varchar(10) DEFAULT NULL COMMENT '国家代码',
    `region` varchar(10) DEFAULT NULL COMMENT '地区或州的短代码（FIPS或ISO）',
    `region_name` varchar(50) DEFAULT NULL COMMENT '地区或州名称',
    `city` varchar(50) DEFAULT NULL COMMENT '城市名称',
    `district` varchar(50) DEFAULT NULL COMMENT '位置的区（郡）',
    `lat` double DEFAULT NULL COMMENT '纬度',
    `lon` double DEFAULT NULL COMMENT '经度',
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间，默认为当前时间戳',
    `updated_at` timestamp NULL DEFAULT NULL COMMENT '更新时间',
    `deleted_at` timestamp NULL DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `id_unique` (`id`),
    KEY `idx_short_url_visits_on_created_at` (`created_at`),
    KEY `idx_short_url_visits_on_short_url` (`short_url`)
) COMMENT '短链访问信息表';