// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package weChatMiniProgram

import (
	"compressURL/api/weChatMiniProgram"
)

type ControllerV1 struct{}

func NewV1() weChatMiniProgram.IWeChatMiniProgramV1 {
	return &ControllerV1{}
}
