apiVersion: apps/v1
kind: Deployment
metadata:
  name: kkdl
  labels:
    app: kkdl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kkdl
  template:
    metadata:
      labels:
        app: kkdl
    spec:
      containers:
        - name : main
          image: kkdl
          imagePullPolicy: Always

