// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"compressURL/internal/dao/internal"
)

// internalShortUrlCodeDao is internal type for wrapping internal DAO implements.
type internalShortUrlCodeDao = *internal.ShortUrlCodeDao

// shortUrlCodeDao is the data access object for table short_url_code.
// You can define custom methods on it to extend its functionality as you wish.
type shortUrlCodeDao struct {
	internalShortUrlCodeDao
}

var (
	// ShortUrlCode is globally public accessible object for table short_url_code operations.
	ShortUrlCode = shortUrlCodeDao{
		internal.NewShortUrlCodeDao(),
	}
)

// Fill with you ideas below.
