// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"compressURL/internal/dao/internal"
)

// internalShortUrlDao is internal type for wrapping internal DAO implements.
type internalShortUrlDao = *internal.ShortUrlDao

// shortUrlDao is the data access object for table short_url.
// You can define custom methods on it to extend its functionality as you wish.
type shortUrlDao struct {
	internalShortUrlDao
}

var (
	// ShortUrl is globally public accessible object for table short_url operations.
	ShortUrl = shortUrlDao{
		internal.NewShortUrlDao(),
	}
)

// Fill with you ideas below.
