// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"compressURL/internal/dao/internal"
)

// internalShortUrlVisitsDao is internal type for wrapping internal DAO implements.
type internalShortUrlVisitsDao = *internal.ShortUrlVisitsDao

// shortUrlVisitsDao is the data access object for table short_url_visits.
// You can define custom methods on it to extend its functionality as you wish.
type shortUrlVisitsDao struct {
	internalShortUrlVisitsDao
}

var (
	// ShortUrlVisits is globally public accessible object for table short_url_visits operations.
	ShortUrlVisits = shortUrlVisitsDao{
		internal.NewShortUrlVisitsDao(),
	}
)

// Fill with you ideas below.
