// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"compressURL/internal/dao/internal"
)

// verificationCodesDao is the data access object for the table verification_codes.
// You can define custom methods on it to extend its functionality as needed.
type verificationCodesDao struct {
	*internal.VerificationCodesDao
}

var (
	// VerificationCodes is a globally accessible object for table verification_codes operations.
	VerificationCodes = verificationCodesDao{internal.NewVerificationCodesDao()}
)

// Add your custom methods and functionality below.
