// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package short_url_visits

import (
	"compressURL/api/short_url_visits"
)

type ControllerV1 struct{}

func NewV1() short_url_visits.IShortUrlVisitsV1 {
	return &ControllerV1{}
}
