// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package analytics

import (
	"compressURL/api/analytics"
)

type ControllerV1 struct{}

func NewV1() analytics.IAnalyticsV1 {
	return &ControllerV1{}
}
