// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package short_url

import (
	"compressURL/api/short_url"
)

type ControllerV1 struct{}

func NewV1() short_url.IShortUrlV1 {
	return &ControllerV1{}
}
