name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # 设置 Go 版本为 1.20

      - name: Install gf-tool
        run: |
          wget -O gf https://github.com/gogf/gf/releases/latest/download/gf_$(go env GOOS)_$(go env GOARCH)
          chmod +x gf 
          ./gf install -y
          rm ./gf

      - name: Build Go application
        run: gf build

      - name: Archive build
        run: |
          cd temp/linux_amd64
          tar -czf main.tar.gz main

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            if [ -e /usr/local/kk/kkdl/main ]; then
              mv /usr/local/kk/kkdl/main /usr/local/kk/kkdl/oldman
            fi
            tar -xzf main.tar.gz
            sudo systemctl stop myapp
            sudo mv main /usr/local/kk/kkdl/
            sudo cd /usr/local/kk/kkdl/
            sudo sh run.sh
            if [ -e /usr/local/kk/kkdl/oldman ]; then
              rm -rf oldman
            fi