name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: true

      - name: Install gf-tool
        run: wget -O gf https://github.com/gogf/gf/releases/latest/download/gf_$(go env GOOS)_$(go env GOARCH) && chmod +x gf && ./gf install -y && rm ./gf

      - name: Build Go application
        run: gf build

      - name: Output build directory
        run: ls

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: build upload
        run: |
          cd ./linux_amd64
          tar -czf main.tar.gz main
          scp -o StrictHostKeyChecking=no -P 22 main.tar.gz ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/kkdl/main.tar.gz

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            if [ -e /opt/kkdl/main ]; then
              mv /opt/kkdl/main /opt/kkdl/oldMan
            fi
            cd /opt/kkdl/
            tar -xzf main.tar.gz
            sh run.sh
            if [ -e /opt/kkdl/oldMan ]; then
              rm -rf oldMan main.tar.gz
            fi